Solution to tasks 03-vue-cli
js-tasks-ru/vue-20201210_ser-lapteff pull request #4
Opened 2021-01-13 13:45 UTC by serlapteff

2021-01-13 13:56 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
DropdownButton-1
+ Компонент должен иметь параметры title, options, value
+ Кнопка должна иметь текст с заголовком из параметра
+ Кнопка должна иметь текст с заголовком и выбранным вариантом
+ Компонент должен реагировать на изменение выбранного варианта
+ Компонент должен показывать список скрытым, открывать его по клику и закрывать по повторному клику
+ Выбор вариант порождает событие change
+ Список должен скрываться после выбора варианта
+ Должен быть класс dropdown__toggle_icon и иконка на кнопке выбранного варианта при наличии icon в списке вариантов
+ Должен быть класс dropdown__item_icon на все вариантах, если хотя бы у одного есть иконка
```
```diff
AppToast
+ AppToast изначально не показывает ни одного тоста
+ AppToast должен выво��ить success тост с сообщением после вызова метода success
+ AppToast должен выводить error тост с сообщением после вызова метода error
+ AppToast должен выводить список тостов в порядке добавления
+ AppToast удалять тост через 5 секунд
```
```diff
CounterButton.vue
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен выводить новое значение счётчика при его обновлении
+ CounterButton должен порождать событие increment с увеличенным на 1 значением после клика
```
```diff
FormGroup
+ FormGroup должен иметь параметры inline, label
+ FormGroup должен выводить содержимое в блоке .form-group
+ FormGroup не должен выводить label по умолчанию
+ FormGroup должен выводить label со значением параметра
+ FormGroup должен выводить слот после label
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2021-01-14 11:13 UTC, ShGKme requested changes
Требуется убрать некорректное использование директивы `v-slot` на `<slot>`.
По остальным задачам тоже есть замечания, можете исправить их на своё усмотрение, или оставить, как есть.

2021-01-14 11:13 UTC, ShGKme commented on 03-vue-cli/02-FormGroup/components/FormGroup.vue
> +    <slot v-slot:default></slot>
Директива `v-slot` используется на элементе `<template>` при передаче содержимого слота, а не на определении слота.

2021-01-14 11:13 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Данное вами имя `computedTitle` явно намекает на то, что это должно быть вычисляемое свойство (`computed`), а не метод.

2021-01-14 11:13 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Хотя этот метод используется только в вычисляемом свойстве, его удобно сделать именно вычисляемым свойством и использовать напрямую в шаблоне.

2021-01-14 11:13 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +        ? this.options.find((el) => el.value === this.value).icon
Поиск элемента с текущим `value` встречается в коде несколько раз. Его тоже удобно сделать самостоятельным вычисляемым свойством.

2021-01-14 11:13 UTC, ShGKme commented on 03-vue-cli/03-AppToast/components/AppToast.vue
> +      <app-icon :icon="getIconToast(toast.type)" />
Лучше избегать вызова метода в шаблоне. Он будет вызываться каждый раз при каждом ререндеринге, а шаблон получается менее декларативным.

В данном случае метод очень простой и не создаст сколько-нибудь заметных проблем с производительностью, но лучше всегда, когда есть простая возможность, избегать использования методов в шаблоне.
 
В данном случае метод легко заменяется данными:
1. Можно положить иконку прямо в объект `toast`
2. Если не хочется засорять этим `toast`, тогда можно хранить отдельный статичный объект, который позволяет по типу получить иконку. `{ success: 'check-circle', ... }`

2021-01-15 12:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-01-15 12:30 UTC, serlapteff commented on 03-vue-cli/02-FormGroup/components/FormGroup.vue
> +    <slot v-slot:default></slot>
Что то я напутал, исправил.

2021-01-15 12:36 UTC, serlapteff commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +    },
computedTitle перенес в вычисляемые свойства, так выглядит логичнее. Почему то сразу до меня это не дошло:)

2021-01-15 12:37 UTC, serlapteff commented on 03-vue-cli/03-AppToast/components/AppToast.vue
> +      <app-icon :icon="getIconToast(toast.type)" />
Добавил иконку в объект, спасибо за разъяснения!

2021-01-15 19:30 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-01-15 19:31 UTC, merged