Solution to tasks 04-SPA
js-tasks-ru/vue-20201210_ser-lapteff pull request #5
Opened 2021-02-08 16:22 UTC by serlapteff

2021-02-10 21:40 UTC, ShGKme commented on 04-SPA/04-Layouts/components/TheHeader.vue
> +  </header>
Кажется, этот код был скопирован с собранного проекта. В него попали дата-атрибуты, которые автоматически добавляются для `scoped` стилей. В этой задаче не страшно, но в проект их добавлять не нужно :)

2021-02-10 21:41 UTC, ShGKme reviewed
Все задачи приняты 👍

2021-02-12 07:05 UTC, ShGKme requested changes
Задача `AppInput` принята 👍
В `BaseButton` есть вопросы по использованию рендер функции...

2021-02-12 07:05 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/SecondaryButton.vue
> +  inheritAttrs: false,
`inheritAttrs: false` нужен, когда требуется не передавать атрибуты на корневой элемент, либо они передаются на некоторый внутренний элемент (как было в `AppInput`, где корневым был просто `div`). Здесь же нужный элемент уже является корневым, и необходимости отключать наследование атрибутов - нет.

2021-02-12 07:05 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  },
Нужна ли здесь рендер функция? Она была добавлена, потому что нет другого решения, или по другой причине?

2021-02-12 07:05 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +        },
Требуется пробросить все установленные обработчики событий, т.е. передать целиком весь `$listeners`

2021-02-15 07:27 UTC, serlapteff commented on 06-deep-vue/01-Buttons/components/SecondaryButton.vue
> +  inheritAttrs: false,
Убрал отключение наследования атрибутов.

2021-02-15 07:30 UTC, serlapteff commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  },
Рендер функцию можно заменить использованием ```<component>```, но не показалось, что здесь довольно удобно использовать рендер функцию.

2021-02-15 07:31 UTC, serlapteff commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +        },
Поправил:
```js
render: function (h) {
    return h(
      this.tag,
      {
        staticClass: "button",
        class: {
          button_block: this.block
        },
        on: this.$listeners,
      },
      this.$slots.default
    )
  }
```

2021-02-16 13:50 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  },
Лучше заменить на шаблон. Здесь решение с шаблоном получается в 1-3 строки, а решение с рендер функцией никак не помогает сделать код лучше (например, если использовать JSX, получится тоже самое, что и в шаблоне, разницы нет).

2021-02-16 13:52 UTC, ShGKme requested changes
Лучше всё-таки реализовать `BaseButton` через шаблон...

2021-02-17 10:21 UTC, ShGKme requested changes
`FadeTransitionGroup` не работает из-за инкапсуляции стилей.
Правило `.fade-list > *` не срабатывает, так как на содержимом не будет дата-атрибутов этого компонента. В этой задаче предлагается просто не использовать инкапсуляцию стилей в этом компоненте.

2021-02-17 10:21 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  </component>
Коротко и изящно 🙂

2021-02-17 10:21 UTC, ShGKme commented on 06-deep-vue/06-Transitions-1/components/FadeTransitionGroup.vue
> +  inheritAttrs: false
`inheritAttrs: false` нужен, когда требуется не передавать атрибуты на корневой элемент, либо они передаются на некоторый внутренний элемент (как было в `AppInput`, где корневым был просто `div`). Здесь же нужный элемент уже является корневым, и необходимости отключать наследование атрибутов - нет.

2021-02-17 19:21 UTC, serlapteff commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  </component>
Да, полностью согласен 🙂

2021-02-17 19:23 UTC, serlapteff commented on 06-deep-vue/06-Transitions-1/components/FadeTransitionGroup.vue
> +  inheritAttrs: false
Ой, опять зачем то поставил, убрал.

2021-02-18 04:43 UTC, ShGKme approved these changes
Принято, но есть комментарии

2021-02-18 04:43 UTC, ShGKme commented on 06-deep-vue/08-Transitions-2/components/FadeTransitionGroup.vue
> +    })
В `vnode.data.class` находится динамическое6 описание классов в том же формате, что и значение `:class` в шаблоне. Например, там может быть `undefined` или массив классов. Во втором случае всё будет работать не очень корректно.

Кстати, кроме использования `data.class`, можно работать с `data.staticClass`, где хранится либо `undefined`, либо обычная строка с перечислением классов через пробел.

2021-02-18 04:43 UTC, ShGKme commented on 06-deep-vue/08-Transitions-2/components/FadeTransitionGroup.vue
> +    })
В данном решении вы не клонируете узлы, а изменяете переданные. В целом работает так же, но лучше клонировать узел.

2021-02-18 04:46 UTC, merged